name: svg listing

on:
  push:
    paths:
      - 'assets/img/svg/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate assets/js/svg-list.js
        run: |
          rm -f assets/js/svg-list.js

          {
            echo "const SVG_FILES = ["
            for f in assets/img/svg/*.svg; do
              echo "    '$(basename "$f")',"
            done
            echo "];"
          } > assets/js/svg-list.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/js/svg-list.js
          git diff --cached --quiet || git commit -m "fix : updating the svg list"
          git push
